services:
  rmm_frontend:
    build: .  # ðŸ‘ˆ Usa el Dockerfile local para construir la imagen
    image: rmm_frontend-react-app  # ðŸ‘ˆ Opcional, asÃ­ la nombra localmente
    container_name: rmm_frontend_container
    restart: always
    expose:
      - "80"
    labels:
      - "traefik.enable=true"
      # ðŸš€ Regla para frontend
      - "traefik.http.routers.revista_front.rule=Host(`revista.metaminingmedia.com`) && PathPrefix(`/`)"
      - "traefik.http.routers.revista_front.entrypoints=web,websecure"
      - "traefik.http.routers.revista_front.tls=true"
      - "traefik.http.routers.revista_front.tls.certresolver=mytlschallenge"
      - "traefik.http.services.revista_front.loadbalancer.server.port=80"
    networks:
      - root_default

networks:
  root_default:
    external: true