services:
  geo_frontend:
    build: .  # ðŸ‘ˆ Usa el Dockerfile local para construir la imagen
    image: geo_frontend-react-app  # ðŸ‘ˆ Opcional, asÃ­ la nombra localmente
    container_name: geo_frontend_container
    restart: always
    expose:
      - "80"
    labels:
      - "traefik.enable=true"
      # ðŸš€ Regla para frontend
      - "traefik.http.routers.geo_front.rule=Host(`geoperuvian.codeauni.com`) && PathPrefix(`/`)"
      - "traefik.http.routers.geo_front.entrypoints=web,websecure"
      - "traefik.http.routers.geo_front.tls=true"
      - "traefik.http.routers.geo_front.tls.certresolver=mytlschallenge"
      - "traefik.http.services.geo_front.loadbalancer.server.port=80"
    networks:
      - root_default

networks:
  root_default:
    external: true